-- Seed baby names data for programmatic SEO
-- Run this in Supabase SQL Editor

INSERT INTO public.names (
  name,
  gender,
  origin,
  meaning,
  characteristics,
  popularity_score
)
VALUES
  ('Oliver', 'male', 'English', 'Olive tree', ARRAY['nature', 'traditional', 'popular'], 95),
  ('Emma', 'female', 'English', 'Universal', ARRAY['traditional', 'popular', 'simple'], 98),
  ('Charlotte', 'female', 'English', 'Free man', ARRAY['traditional', 'elegant', 'popular'], 92),
  ('William', 'male', 'English', 'Resolute protector', ARRAY['strength', 'traditional', 'royal'], 90),
  ('Ava', 'female', 'English', 'Life', ARRAY['simple', 'modern', 'popular'], 94),
  ('Louis', 'male', 'French', 'Renowned warrior', ARRAY['traditional', 'royal', 'strength'], 75),
  ('Sophie', 'female', 'French', 'Wisdom', ARRAY['wisdom', 'elegant', 'classic'], 82),
  ('Amelie', 'female', 'French', 'Hard working', ARRAY['virtue', 'elegant', 'unique'], 68),
  ('Marcel', 'male', 'French', 'Little warrior', ARRAY['strength', 'traditional', 'vintage'], 45),
  ('Leonardo', 'male', 'Italian', 'Brave lion', ARRAY['strength', 'traditional', 'bold'], 78),
  ('Isabella', 'female', 'Italian', 'Devoted to God', ARRAY['virtue', 'elegant', 'popular'], 88),
  ('Matteo', 'male', 'Italian', 'Gift of God', ARRAY['virtue', 'traditional', 'popular'], 80),
  ('Gianna', 'female', 'Italian', 'God is gracious', ARRAY['virtue', 'elegant', 'modern'], 76),
  ('Mateo', 'male', 'Spanish', 'Gift of God', ARRAY['virtue', 'traditional', 'popular'], 85),
  ('Sofia', 'female', 'Spanish', 'Wisdom', ARRAY['wisdom', 'elegant', 'popular'], 96),
  ('Santiago', 'male', 'Spanish', 'Saint James', ARRAY['virtue', 'traditional', 'strong'], 72),
  ('Lucia', 'female', 'Spanish', 'Light', ARRAY['virtue', 'elegant', 'classic'], 70),
  ('Felix', 'male', 'German', 'Happy and fortunate', ARRAY['virtue', 'classic', 'cheerful'], 65),
  ('Frieda', 'female', 'German', 'Peace', ARRAY['peace', 'vintage', 'unique'], 42),
  ('Otto', 'male', 'German', 'Wealthy', ARRAY['traditional', 'vintage', 'strong'], 38),
  ('Sven', 'male', 'Scandinavian', 'Young warrior', ARRAY['strength', 'traditional', 'bold'], 35),
  ('Freya', 'female', 'Scandinavian', 'Noble lady', ARRAY['mythological', 'strong', 'unique'], 58),
  ('Lars', 'male', 'Scandinavian', 'Crowned with laurel', ARRAY['traditional', 'strong', 'simple'], 40),
  ('Astrid', 'female', 'Scandinavian', 'Divinely beautiful', ARRAY['virtue', 'unique', 'strong'], 52),
  ('Noah', 'male', 'Jewish', 'Rest and comfort', ARRAY['peace', 'biblical', 'popular'], 97),
  ('Sarah', 'female', 'Jewish', 'Princess', ARRAY['virtue', 'biblical', 'traditional'], 86),
  ('Elijah', 'male', 'Jewish', 'My God is Yahweh', ARRAY['virtue', 'biblical', 'strong'], 91),
  ('Hannah', 'female', 'Jewish', 'Grace', ARRAY['virtue', 'biblical', 'classic'], 84),
  ('Benjamin', 'male', 'Jewish', 'Son of the right hand', ARRAY['virtue', 'biblical', 'popular'], 89),
  ('Amir', 'male', 'Arabic', 'Prince', ARRAY['virtue', 'strong', 'regal'], 62),
  ('Layla', 'female', 'Arabic', 'Night', ARRAY['nature', 'poetic', 'beautiful'], 74),
  ('Omar', 'male', 'Arabic', 'Flourishing', ARRAY['virtue', 'strong', 'traditional'], 58),
  ('Zara', 'female', 'Arabic', 'Princess', ARRAY['virtue', 'elegant', 'modern'], 72),
  ('Arjun', 'male', 'Indian', 'Bright and shining', ARRAY['virtue', 'mythological', 'strong'], 55),
  ('Priya', 'female', 'Indian', 'Beloved', ARRAY['love', 'traditional', 'beautiful'], 48),
  ('Dev', 'male', 'Indian', 'Divine', ARRAY['virtue', 'simple', 'spiritual'], 42),
  ('Anaya', 'female', 'Indian', 'Caring', ARRAY['virtue', 'modern', 'gentle'], 64),
  ('Haruto', 'male', 'Japanese', 'Sun flying', ARRAY['nature', 'strong', 'unique'], 38),
  ('Sakura', 'female', 'Japanese', 'Cherry blossom', ARRAY['nature', 'beautiful', 'poetic'], 46),
  ('Kenji', 'male', 'Japanese', 'Intelligent second son', ARRAY['wisdom', 'traditional', 'strong'], 32),
  ('Yuki', 'unisex', 'Japanese', 'Snow', ARRAY['nature', 'pure', 'beautiful'], 40),
  ('Wei', 'unisex', 'Chinese', 'Great', ARRAY['virtue', 'simple', 'strong'], 35),
  ('Mei', 'female', 'Chinese', 'Beautiful', ARRAY['virtue', 'simple', 'elegant'], 44),
  ('Li', 'unisex', 'Chinese', 'Strength', ARRAY['strength', 'simple', 'traditional'], 38),
  ('Kofi', 'male', 'African', 'Born on Friday', ARRAY['traditional', 'unique', 'cultural'], 28),
  ('Amara', 'female', 'African', 'Grace', ARRAY['virtue', 'beautiful', 'unique'], 56),
  ('Kwame', 'male', 'African', 'Born on Saturday', ARRAY['traditional', 'unique', 'cultural'], 25),
  ('Zuri', 'female', 'African', 'Beautiful', ARRAY['virtue', 'simple', 'modern'], 62),
  ('Vladimir', 'male', 'Slavic', 'Ruler of the world', ARRAY['strength', 'traditional', 'regal'], 42),
  ('Anastasia', 'female', 'Slavic', 'Resurrection', ARRAY['virtue', 'elegant', 'traditional'], 68),
  ('Dimitri', 'male', 'Slavic', 'Follower of Demeter', ARRAY['mythological', 'strong', 'traditional'], 38),
  ('Dakota', 'unisex', 'Native American', 'Friend', ARRAY['virtue', 'nature', 'unique'], 52),
  ('Mika', 'unisex', 'Native American', 'Intelligent raccoon', ARRAY['nature', 'wisdom', 'unique'], 48),
  ('Liam', 'male', 'English', 'Strong-willed warrior', ARRAY['strength', 'popular', 'modern'], 99),
  ('Olivia', 'female', 'English', 'Olive tree', ARRAY['nature', 'popular', 'elegant'], 100),
  ('Amelia', 'female', 'English', 'Work', ARRAY['virtue', 'vintage', 'popular'], 93),
  ('Mia', 'female', 'Italian', 'Mine', ARRAY['love', 'simple', 'popular'], 92),
  ('James', 'male', 'English', 'Supplanter', ARRAY['traditional', 'classic', 'popular'], 87),
  ('Harper', 'female', 'English', 'Harp player', ARRAY['musical', 'modern', 'popular'], 85),
  ('River', 'unisex', 'English', 'Flowing body of water', ARRAY['nature', 'modern', 'peaceful'], 58),
  ('Willow', 'female', 'English', 'Willow tree', ARRAY['nature', 'gentle', 'modern'], 72),
  ('Jasper', 'male', 'English', 'Treasurer', ARRAY['nature', 'vintage', 'unique'], 54),
  ('Ivy', 'female', 'English', 'Faithfulness', ARRAY['nature', 'virtue', 'classic'], 66),
  ('Rowan', 'unisex', 'English', 'Little red one', ARRAY['nature', 'modern', 'unique'], 60),
  ('Luna', 'female', 'Spanish', 'Moon', ARRAY['nature', 'mystical', 'popular'], 78),
  ('Grace', 'female', 'English', 'Charm', ARRAY['virtue', 'classic', 'elegant'], 80),
  ('Hope', 'female', 'English', 'Expectation', ARRAY['virtue', 'simple', 'classic'], 68),
  ('Faith', 'female', 'English', 'Trust', ARRAY['virtue', 'simple', 'classic'], 64),
  ('Justice', 'unisex', 'English', 'Righteousness', ARRAY['virtue', 'strong', 'modern'], 48),
  ('Max', 'male', 'English', 'Greatest', ARRAY['strength', 'simple', 'modern'], 70),
  ('Zoe', 'female', 'English', 'Life', ARRAY['virtue', 'simple', 'popular'], 76),
  ('Kai', 'unisex', 'Japanese', 'Sea', ARRAY['nature', 'simple', 'modern'], 68),
  ('Leo', 'male', 'English', 'Lion', ARRAY['strength', 'simple', 'popular'], 82)
ON CONFLICT (name) DO NOTHING;
